### PR TITLE
src: modify to use nodeshift instead of docker and oc

### PR DESCRIPTION
**Pull request by lance**
Also add kube-probe for health and readiness checks.

### CODE REVIEW

**Comment by rafabene** [comment]
@lance Can you resend your PR but without removing the Dockerfile for now, otherwise it will break our ansible scripts.

The nodeshift needs to be an option as Fabric8-Maven-plugin is for Java microservices. so I would like to ask to not modify Readme.md. Instead I ask to modify the following instruction: https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/bonjour.adoc

As an example of Fabric8-Maven-plugin as a second option, please look at this instruction: https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/aloha.adoc

**Comment by rafabene** [comment]
If you change the health check endpoints, also update the following file: https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/ansible/vars.yml#L50

**Comment by lance** [comment]
@rafabene can you explain what your Ansible scripts do that requires the Dockerfile? The issue we have at this point is that the `centos7-nodejs` Docker image repo is no longer maintained, and in fact has been removed from Docker hub. If the `Dockerfile` remains in this repository, then we will need to replace the `FROM` line with another, well-maintained Node.js Docker image. For this, I suggest using https://hub.docker.com/_/node/. That of course might mean that the `Dockerfile` in this repository may need modification to support labels and other similar attributes previously provided by `centos7-nodejs`.

Regarding the README.md, could it not offer both alternatives, similar to what you suggest for `bonjour.adoc`? I would like to see wider adoption of `nodeshift`, as this is generally the direction we have been going as a team recently, and having it as part of the overall MSA documentation for Node.js services is a good way to do that, IMO.

Regarding the healthcheck endpoints, currently OpenShift supports both health and readiness checks. However, the `YAML` file you reference only specifies `probe`. It is not clear whether this should be for health checks or readiness checks. I am happy to change that `YAML` file, but I wonder if that's the right thing to do. Shouldn't all of the other services be modified to keep up with what OpenShift supports?

**Comment by rafabene** [comment]
The usage of  https://hub.docker.com/_/node/ image has been implemented at https://github.com/redhat-helloworld-msa/bonjour/commit/eda45d8748ed9581e617008393640d20dbae34a9

The ansible script uses oc binary builds for all microservices: https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/ansible/helloworld-msa.yml#L42-L49

I agree that `probe` is not good name, but just for clarification, it set the readiness probe only.

We can promote nodeshift, but the binary build should continue to be supported for a while. helloworld-msa is going to be under maintenance mode and the nodeshift can be added as an additional option.

There's a new architecture for microservices 3.0 that are being implemented at https://github.com/redhat-msa-3. This is where we will be focusing all the things that we like to promote for the 3.0 architecture. There's a nodeJS microservice at https://github.com/redhat-msa-3/catalog-microservice

**Comment by lance** [comment]
@rafabene looking at the current `master` it seems as though you have already taken care of everything that you requested in your initial comment. Is that the case, or is there something else you would like me to do here?

**Comment by rafabene** [comment]
The current master doesn't support kube-probe and nodeshift. Can you add them back as I reverted the merge from this PR?

**Comment by lance** [comment]
@rafabene will do.

**Pull request merged**
